pipeline {
    options {
        // set a timeout of 30 minutes for this pipeline
        timeout(time: 30, unit: 'MINUTES')
    }
    agent {
      node {
        label 'master'
      }
    }
    stages {
        stage('OpenShift project') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                                echo "stage 1: using project: ${openshift.project()} in cluster ${openshift.cluster()} with name ${_NAME}"
                        }
                    }
                }
            }
        }

      stage('Default session dump empty') {
        steps {
              sh '[[ "$(curl http://$(oc get route ${_NAME})/hpe5g.html/dump)" == "[]" ]]'
          }
      }
      stage('Error on invalid session') {
        steps {
              sh '[[ $(curl http://$(oc get route ${_NAME})/unlikely.html/dump) != 0 ]]'
          }
      }

      stage('Manual approval') {
        steps {
          timeout(time: 60, unit: 'MINUTES') {
          input message: "Confirm success?"
          }
        }
      }
    }
}
