def _ENDPOINT = "undefined"

pipeline {
    options {
        // set a timeout of 30 minutes for this pipeline
        timeout(time: 30, unit: 'MINUTES')
    }
    agent {
      node {
        label 'master'
      }
    }
    stages {
        stage('OpenShift context') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                          _ENDPOINT = openshift.selector( 'route/${_NAME}').object().spec.host
                          echo "OpenShift context: using project ${openshift.project()} in cluster ${openshift.cluster()} with name ${_NAME} and route ${_ENDPOINT}"
                        }
                    }
                }
            }
        }

      stage('Get default and bs-set session dump') {
        steps {
              sh """
              [[ \$(curl http://${_ENDPOINT}/hpe5g.html/dump) == [] ]]
              curl http://${_ENDPOINT}/bs-set.html/dump
              """
          }
      }
      stage('Deploy bs-set') {
        steps {
              sh "curl -X PUT -H \"Content-Type: application/json\" http://${_ENDPOINT}/bs-set.html/deploy?project=bs-set"
          }
      }
      stage('Get error on invalid session') {
        steps {
              sh "[[ \$(curl http://${_ENDPOINT}/unlikely.html/dump) != 0 ]]"
          }
      }

      stage('Manual approval') {
        steps {
          timeout(time: 60, unit: 'MINUTES') {
          input message: "Confirm success?"
          }
        }
      }
    }
}
